# Generated by Django 4.0.6 on 2022-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dollar', models.FloatField()),
                ('date', models.CharField(max_length=256)),
                ('rub', models.FloatField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
